config/routes.rb
Rails.application.routes.draw do
  
  get 'profiles/edit'
  get 'users/index'
  get 'users/show'
  root 'homes#index'
  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions => 'users/sessions',
   :omniauth_callbacks => 'users/omniauth_callbacks'
  }

  resources :users do
    resources :profiles, only: [:edit, :update]
    resources :healths
      get 'healths/:id/edit_body', to: 'healths#edit_body', as: 'healths_edit_body'
      patch 'healths/:id/update_body', to: 'healths#update_body', as: 'healths_update_body'
      get 'healths/:id/edit_sleep', to: 'healths#edit_sleep', as: 'healths_edit_sleep'
      patch 'healths/:id/update_sleep', to: 'healths#update_sleep', as: 'healths_update_sleep'
      get 'healths/:id/edit_water', to: 'healths#edit_water', as: 'healths_edit_water'
      patch 'healths/:id/update_water', to: 'healths#update_water', as: 'healths_update_water'
      get 'healths/:id/edit_day', to: 'healths#edit_day', as: 'healths_edit_day'
      patch 'healths/:id/update_day', to: 'healths#update_day', as: 'healths_update_day'
  end
  resources :articles
end

app/models/health.rb
class Health < ApplicationRecord
  belongs_to :user
  
  validates :day, presence: true

  validate :getuptime_at_is_invalid_without_a_bedtime_at

  def getuptime_at_is_invalid_without_a_bedtime_at
    errors.add(:bedtime_at, "が必要です") if bedtime_at.blank? && getuptime_at.present?
  end
  
end

app/controllers/healths_controller.rb
class HealthsController < ApplicationController
  before_action :user_id, only: [:edit, :edit_body, :update_body, :edit_sleep, :update_sleep, 
                                 :edit_water, :update_water, :edit_goal, :update_goal,
                                 :edit_day, :update_day
                                 ]
  before_action :health_find, only: [:edit, :update, :destroy, :edit_body, :update_body,
                                     :edit_sleep, :update_sleep, :edit_water, :update_water,
                                     :edit_goal, :update_goal, :edit_day, :update_day
                                     ]
  before_action :authenticate_user!


  def edit
    @profile = Profile.find_by(id: current_user.id)
  end
  
  def update
    
  end
  
  def edit_body
  end
  
  def update_body
    if @health.update(health_body_params)
      flash[:notice] = "体情報を登録しました。"
      redirect_to  user_path @user
    else
      flash[:alert] =  "体情報の登録に失敗しました。"
      render :edit_body
    end
  end

  def edit_sleep
  end
  
  def update_sleep
    if @health.update(health_sleep_params)
      flash[:notice] = "睡眠情報を登録しました。"
      redirect_to  user_path @user
    else
      flash[:alert] = "睡眠情報の登録に失敗しました。"
      render :edit_sleep
    end
  end

  def edit_water
  end
  
  def update_water
    if @health.update(health_water_params)
      flash[:notice] = "水分情報を登録しました。"
      redirect_to  user_path @user
    else
      flash[:alert] = "水分情報の登録に失敗しました。"
      render :edit_water
    end
  end

  def edit_goal
  end
  
  def update_goal
    if @health.update(health_goal_params)
      flash[:notice] = "目標情報を登録しました。"
      redirect_to  user_path @user
    else
      flash[:alert] = "目標情報の登録に失敗しました。"
      render :edit_goal
    end
  end
  
  def edit_day
  end
  
  def update_day
    if @health.update_attributes!(health_day_params)
      flash[:notice] = "更新しました。"
      redirect_to  user_path @user
    else
      flash[:alert] = "更新に失敗しました。"
      redirect_to user_path @user
    end
  end
  
  def destroy
  end
  
  private
    def user_id 
      health = Health.find_by(user_id: current_user.id)
      @user = health.user_id
    end
    
    def health_find
      @health = Health.find(params[:id])
    end
    
    def health_body_params
      params.require(:health).permit(:weight, :body_fat, :bowel_movement)
    end
    
    def health_sleep_params
      params.require(:health).permit(:bedtime_at, :getuptime_at)
    end

    def health_water_params
      params.require(:health).permit(:water)
    end

    def health_goal_params
      params.require(:health).permit(:weight_goal, :body_fat_goal)
    end
    
    def health_day_params
      params.require(:health).permit(:weight, :body_fat, :bedtime_at, :getuptime_at,
                                     :bowel_movement, :water)
    end
end

app/helpers/healths_helper.rb
module HealthsHelper
  def sleeping_time(h, bedtime, getup)
    if bedtime < getup
      h.sleep_at = (((getup - bedtime) / 60) /60)
    else
      h.sleep_at = (((getup - bedtime) / 60) /60) + 24
    end
  end
end

app/views/healths/_edit.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-dialog modal-guidance">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">登録メニュー</h5>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      </div>
      <div class="modal-body">
        <p class="btn-body">
          <%= link_to "体情報", user_healths_edit_body_path(@user, @health), remote: true, class: "btn-circle-flat" %>
        </p>
        <div class="d-flex">
          <p class="btn-sleep">
            <%= link_to "睡眠情報", user_healths_edit_sleep_path(@user, @health), remote: true, class: "btn-circle-flat" %>
          </p>
          <p class="btn-water">
            <%= link_to "水分", user_healths_edit_water_path(@user, @health), remote: true, class: "btn-circle-flat" %>
          </p>
        </div>
          <p class="btn-goal">
            <%= link_to "目標編集", edit_user_profile_path(@user, @profile), remote: true, class: "btn-top-radius w-50" %>
          </p>
      </div>
    </div>
  </div>
</div>

<!-- 目標編集 -->
<div class="modal fade" id="profile_edit" tabindex="-1" role="dialog" aria-hidden="true">
  <%= render 'profiles/edit' %>
</div>

<!-- 体情報 -->
<div id="edit_body" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <%= render 'healths/edit_body' %>
</div>

<!-- 睡眠情報 -->
<div id="edit_sleep" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <%= render 'healths/edit_sleep' %>
</div>

 <!--水分 -->
<div class="modal fade" id="edit_water" tabindex="-1" role="dialog" aria-hidden="true">
  <%= render 'healths/edit_water' %>
</div>

<script>
$(document).ready(function () {
  $(document).on('show.bs.modal', '.modal', e => {
    const $currentModal = $(e.currentTarget);
    var zIndex = 1040 + (10 * $('.modal:visible').length);
    $currentModal.css('z-index', zIndex);
    setTimeout(function() {
      $('.modal-backdrop')
        .not('.modal-stack')
        .css('z-index', zIndex - 1)
        .addClass('modal-stack');
    }, 0);
  });
});
</script>

app/views/healths/_edit_body.html.erb
<div class="modal-dialog modal-width">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">体情報</h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      </div>
      <div class="modal-body">
        <%= form_with model: @health, url: user_healths_update_body_path(@user, @health), method: :patch do |f| %>
          <div>
            <form>
              <div class="form-group">
                <%= f.label :weight %>
                <%= f.number_field :weight, step: "0.1", class: "form-control", min: 1, max: 150,
                                                                   autofocus: true,
                                                                   required: true %>
              </div>
              <div class="form-group">
                <%= f.label :body_fat %>
                <%= f.number_field :body_fat, step: "0.1", class: "form-control", min: 0, max: 30 %>
              </div>
              <div class="form-check">
                <%= f.label :bowel_movement, class: "form-check-label" %>
                <%= f.check_box :bowel_movement, {}, true, false %>
              </div>
              <div class="form-group btn-body mt-5">
                <%= f.submit "登録", class: "btn-flat-border w-50" %>
                <button type="button" class="bbtn-cancel-border" data-dismiss="modal">
                  キャンセル
                </button>
              </div>
            </form>
          </div>
        <% end %>
      </div>
    </div>
  </div>

        

app/views/healths/_edit_day.html.erb
<div class="modal-dialog modal-width">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"><%= l(@health.day, format: :long) %>の編集</h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      </div>
      <div class="modal-body">
        <%= form_with model: @health, url: user_healths_update_day_path(@user, @health) do |f| %>
        <table class="table table-bordered table-condensed health_day_table" id="table-healths">
          <thead>
            <tr>
              <th rowspan="2">日付</th>
              <th rowspan="2">曜日</th>
              <th colspan="2">体情報</th>
              <th colspan="3">睡眠情報</th>
              <th rowspan="2">水分</th>
              <th rowspan="2">お通じ</th>
            </tr>
            <tr>
              <th>体重</th>
              <th>体脂肪</th>
              <th>就寝時間(前日)</th>
              <th>起床時間</th>
              <th>睡眠時間</th>
            </tr>
          </thead>
      
          <tbody>
            <tr>
              <!-- 日付 -->
              <td class='<%= css_class(@health.day) %> pr-0 pl-0'><%= l(@health.day, format: :short) %></td>
              <!-- 曜日 -->
              <td class='<%= css_class(@health.day) %>'>
                <%= $days_of_the_week[@health.day.wday] %>
              </td>
              <!-- 体重 -->
              <td>
                <%= f.number_field :weight, step: "0.1", class: "form-control", min: 1, max: 150,
                                                                 autofocus: true %>
              </td>
              <!-- 体脂肪 -->
              <td>
                <%= f.number_field :body_fat, step: "0.1", class: "form-control", min: 0, max: 30 %>
              </td>
              <!-- 就寝時間 -->
              <td>
                <%= f.time_field :bedtime_at, class: "form-control" %>
              </td>
              <!-- 起床時間 -->
              <td>
                <%= f.time_field :getuptime_at, class: "form-control" %>
              </td>
              <!-- 睡眠時間 -->
              <td>
                <% if @health.bedtime_at.present? && @health.getuptime_at.present? %>
                  <%= sleeping_time(@health, @health.bedtime_at, @health.getuptime_at) %>
                <% end %>
              </td>
              <!-- 水分 -->
              <td>
                <%= f.check_box :water, {}, true, false %>
              </td>
              <!-- お通じ -->
              <td>
                <%= f.check_box :bowel_movement, {}, true, false %>
              </td>
            </tr>
          </tbody>
        </table>
        <div class="edit-day-btn">
          <%= f.submit class: "btn btn-flat-border w-50" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/healths/_edit_goal.html.erb
<div class="modal-dialog modal-width">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title">目標編集</h4>
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    </div>
    <div class="modal-body">
      <%= form_with model: @health, url: user_healths_update_goal_path(@user, @health), method: :patch do |f| %>
      <form>
        <div class="form-group">
          <%= f.label :weight_goal, "目標体重" %>
          <%= f.number_field :weight_goal, class: "form-control",
                                            step: "0.1",
                                        required: true %>
        </div>
        <div class="form-group">
          <%= f.label :body_fat_goal, "目標体脂肪" %>
          <%= f.number_field :body_fat_goal, class: "form-control",
                                              step: "0.1",
                                          required: true %>
        </div>
        <div class="form-group text-center">
          <%= f.submit "登録", class: "btn-flat-border w-50" %>
          <button type="button" class="bbtn-cancel-border" data-dismiss="modal">
            キャンセル
          </button>
        </div>
      </form>
      <% end %>
    </div>
  </div>
</div>


        

app/views/healths/_edit_sleep.html.erb
<div class="modal-dialog modal-width">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title">睡眠情報</h4>
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    </div>
    <div class="modal-body">
    <%= form_with model: @health, url: user_healths_update_sleep_path(@user, @health) do |f| %>
    <form>
      <div class="form-group">
          <%= f.label :bedtime_at, "前日の就寝時間" %>
          <%= f.time_field :bedtime_at, class: "form-control", 
                                    autofocus: true,
                                     required: true %>
      </div>
      <div class="form-group">
        <%= f.label :getuptime_at %>
        <%= f.time_field :getuptime_at, class: "form-control" %>
      </div>
      <div class="form-group text-center">
        <%= f.submit "登録", class: "btn-flat-border w-50" %>
        <button type="button" class="bbtn-cancel-border" data-dismiss="modal">
          キャンセル
        </button>
      </div>
    </form>
    <% end %>
    </div>
  </div>
</div>

app/views/healths/_edit_water.html.erb
<div class="modal-dialog modal-width">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title">水分補給の記録</h4>
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    </div>
    <div class="modal-sub-header">
      <h6 class="modal-sub-title">目標水分量：3.0L</h6>
    </div>
    <div class="modal-body">
      <div>
        <%= form_with model: @health, url: user_healths_update_water_path(@user, @health) do |f| %>
        <form class="form-horizontal">
          <div class="form-group">
            <%= f.label "摂取あり" %>
            <%= f.radio_button :water, true %>
          </div>
          <div class="form-group">
            <%= f.label "摂取なし" %>
            <%= f.radio_button :water, false %>
          </div>
          <div class="form-group">
            <%= f.submit "登録", class: "btn-flat-border w-50" %>
            <button type="button" class="bbtn-cancel-border" data-dismiss="modal">
              キャンセル
            </button>
          </div>
        </form>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/healths/edit.js.erb
$("#edit").html("<%= escape_javascript(render 'edit') %>");
$("#edit").modal("show");

app/views/healths/edit_body.js.erb
$("#edit_body").html("<%= escape_javascript(render 'edit_body') %>");
$("#edit_body").modal("show");

app/views/healths/edit_day.js.erb
$("#edit_day").html("<%= escape_javascript(render 'edit_day') %>");
$("#edit_day").modal("show");

app/views/healths/edit_goal.js.erb
$("#edit_goal").html("<%= escape_javascript(render 'edit_goal') %>");
$("#edit_goal").modal("show");

app/views/healths/edit_sleep.js.erb
$("#edit_sleep").html("<%= escape_javascript(render 'edit_sleep') %>");
$("#edit_sleep").modal("show");

app/views/healths/edit_water.js.erb
$("#edit_water").html("<%= escape_javascript(render 'edit_water') %>");
$("#edit_water").modal("show");