config/routes.rb
Rails.application.routes.draw do
  
  get 'profiles/edit'
  get 'users/index'
  get 'users/show'
  root 'homes#index'
  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions => 'users/sessions',
   :omniauth_callbacks => 'users/omniauth_callbacks'
  }

  resources :users do
    resources :profiles, only: [:edit, :update]
    resources :healths
      get 'healths/:id/edit_body', to: 'healths#edit_body', as: 'healths_edit_body'
      patch 'healths/:id/update_body', to: 'healths#update_body', as: 'healths_update_body'
      get 'healths/:id/edit_sleep', to: 'healths#edit_sleep', as: 'healths_edit_sleep'
      patch 'healths/:id/update_sleep', to: 'healths#update_sleep', as: 'healths_update_sleep'
      get 'healths/:id/edit_water', to: 'healths#edit_water', as: 'healths_edit_water'
      patch 'healths/:id/update_water', to: 'healths#update_water', as: 'healths_update_water'
      get 'healths/:id/edit_day', to: 'healths#edit_day', as: 'healths_edit_day'
      patch 'healths/:id/update_day', to: 'healths#update_day', as: 'healths_update_day'
  end
  resources :articles
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i(google_oauth2)
         
  has_one :profile, dependent: :destroy
  has_many :articles, dependent: :destroy
  has_many :healths, dependent: :destroy
  
  delegate :name, to: :profile
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end
  
  # callback for google
  def google_oauth2
    callback_for(:google)
  end
  
  # common callback method
  def callback_for(provider)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    if resource
      profile = Profile.new
      profile.user_id = resource.id
      profile.name = params[:user][:profile][:name]
      profile.save
    end
    # puts "======= #{params[:user][:profile]} ========"
    # puts "======== #{profile.name = } ========"
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    super
    user = User.find_by(id: resource.id)
    profile = Profile.find_by(id: user.id)
    profile.update(name: params[:user][:profile][:name])
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected
  
  def update_resource(resource, params)
    if resource.password.blank?  # 名前を持たないユーザーは現在のパスワード確認なし #
      resource.update_without_password(params)
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_find, only: [:show, :edit]
  before_action :authenticate_user!
  before_action :correct_user
  before_action :set_one_month, only: [:show, :edit]

  def index
    
  end

  def show
    # 今日の体情報
    @health = @user.healths.find_by(day: Date.current)
    # 本番環境でgoogle認証した場合にprofileを生成
    @user = Health.find_by(user_id: current_user.id)
    @profile = Profile.find_by(user_id: current_user.id)
    if @profile.blank?
      @profile = Profile.new
      @profile.id = current_user.id
      @profile.user_id = current_user.id
      @profile.save
    end
    # グラフ
    @user_data = @healths.where.not(weight: nil)
    weights = @healths.pluck(:weight)
    unless weights.all?(&:nil?)
      @min = weights.compact.min - 10
      @max = weights.compact.max + 10
    end
  end
  
  def edit
    @health = @user.healths.find_by(day: Date.today)
    @user = Health.find_by(user_id: current_user.id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, '履歴') %>
<% provide(:home, 'history') %>
<% provide(:navbar_text, 'black') %>

<div class="container">
  <div class="table-area">
  <div class="col-12">
    <div class="w-50"><%= render 'shared/flash_messages' %></div>
    <h1 class="text-center health-top">履歴</h1>
    
    <table class="table table-bordered table-condensed table-hover table-striped" id="table-healths">
      <thead>
        <tr>
          <!--<th rowspan="2">日付</th>-->
          
          <!--<th rowspan="2">曜日</th>-->
          
          <!--<th colspan="2">体情報</th>-->
          <!--<th>体情報</th>-->
          <!--<th colspan="3">睡眠情報</th>-->
          <!--<th>睡眠情報</th>-->
          <!--<th rowspan="2">水分</th>-->
          
          <!--<th rowspan="2">お通じ</th>-->
          
          <!--<th rowspan="2">編集</th>-->
          
        </tr>
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th>体重</th>
          <th>体脂肪</th>
          <th>就寝時間(前日)</th>
          <th>起床時間</th>
          <th>睡眠時間</th>
          <th>水分</th>
          <th>お通じ</th>
          <th>編集</th>
        </tr>
      </thead>
    
      <tbody>
        <% @healths.each do |h| %>
          <tr>
            <!-- 日付 -->
            <td class='<%= css_class(h.day) %> pr-0 pl-0'><%= l(h.day, format: :short) %></td>
            <!-- 曜日 -->
            <td class='<%= css_class(h.day) %>'>
              <%= $days_of_the_week[h.day.wday] %>
            </td>
            <!-- 体重 -->
            <td>
              <% if h.weight.present? %>
                <%= h.weight %>
                <%= 'kg' %>
              <% end %>
            </td>
            <!-- 体脂肪 -->
            <td>
              <% if h.body_fat.present? %>
                <%= h.body_fat %>
                <%= '%' %>
              <% end %>
            </td>
            <!-- 就寝時間 -->
            <td>
              <% if h.bedtime_at.present?  %>
                <%= l(h.bedtime_at, format: :short) %>
              <% end %>
            </td>
            <!-- 起床時間 -->
            <td>
              <% if h.getuptime_at.present? %>
                <%= l(h.getuptime_at, format: :short) %>
              <% end %>
            </td>
            <!-- 睡眠時間 -->
            <td>
              <% if h.bedtime_at.present? && h.getuptime_at.present? %>
                <%= sleeping_time(h, h.bedtime_at, h.getuptime_at) %>
              <% end %>
            </td>
            <!-- 水分 -->
            <td>
              <% if h.water == true %>
                <%= "摂取あり" %>
              <% end %>
            </td>
            <!-- お通じ -->
            <td>
              <% if h.bowel_movement == true %>
                <%= "あり" %>
              <% end %>
            </td>
            <!-- 編集 -->
            <td>
              <div>
              <% if h.day <= Date.today %>
                <%= link_to "編集", user_healths_edit_day_path(@user.user_id, h.id), remote: true, 
                                                                                      class: "btn btn-success btn-sm" %>
              <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  </div>
</div>

<div id="edit_day" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<% provide(:title, 'Health一覧') %>
<% provide(:home, '') %>
<% provide(:navbar_text, 'black') %>

<div class="container">
  <h1 class="text-center health-top">Health</h1>
  <div class="row mb-5">
    <div class="col-sm-12 col-md-6 col-lg-7">
      <div class="health-graph-item">
        <h3 class="user-edit-center">
          <%= link_to user_path(date: @first_day.prev_month), class: "month" do %>
            <%= icon("fa", "arrow-left") %>
          <% end %>
          <%= @first_day.strftime("%m月") %>
          <%= link_to user_path(date: @first_day.next_month), class: "month" do %>
            <%= icon("fa", "arrow-right") %>
          <% end %>
        </h3>
        <div>
          <% if @user_data.present? %>
            <%= line_chart @user_data.pluck(:day, :weight), min: @min, 
                                                            max: @max, 
                                                            curve: false %>
          <% else %>
            <%= line_chart @healths.pluck(:day, :weight) %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-sm-12 col-md-6 col-lg-5">
      <div class="health-body-item">
        <table class="table table-bordered">
          <h3 class="user-edit-center">今日の体情報</h3>
          <tr>
            <td class="weight">
              <p class="text-left goal-mb">体重</p>
              <p class="goal-font">
                <% if @health.weight.present? %>
                  <%= @health.weight %>
                <% else %>
                  -- --
                <% end %>
              </p>
              <p class="text-right goal-mb">kg</p>
              </div>
            </td>
            <td class="body-fat">
              <p class="text-left goal-mb">体脂肪</p>
            <p class="goal-font">
              <% if @health.body_fat.present? %>
                <%= @health.body_fat %>
              <% else %>
                -- --
              <% end %>
            </p>
            <p class="text-right goal-mb"> % </p>
            </td>
          </tr>
          <tr class="goal">
            <td class="weight-goal">
              <p class="mb-1 goal-name">目標体重</p>
              <div class="target text-right">
                <p class="goal-integer">
                  <% if @profile.present? %>
                    <% if  @profile.weight_goal.blank? %>
                      -- -- 
                    <% else %>
                      <%= @profile.weight_goal %>
                    <% end %>
                  <% else %>
                    -- --
                  <% end %>
                </p>
                <p class="mb-0">kg</p>
              </div>
            </td>
            <td class="bodyfat-goal">
              <p class="mb-1 goal-name">目標体脂肪</p>
              <div class="target text-right">
                <p class="goal-integer">
                  <% if @profile.present? %>
                    <% if @profile.body_fat_goal.blank? %>
                      -- --
                    <% else %>
                      <%= @profile.body_fat_goal %>
                    <% end %>
                  <% else %>
                    -- --
                  <% end %>
                </p>
                <p class="per"> % </p>
              </div>
            </td>
          </tr>
        </table>
        <div class="btn-center">
          <%= link_to "登録", edit_user_health_path(@user.user_id, @health), remote: true, class: "btn btn-lg btn-primary w-50 m-auto" %>
        </div>
      </div>
    </div>
  </div>
    
  
  <div class="row">
    <div class="col-12 d-none d-md-block">
    <table class="table table-bordered table-condensed table-hover table-striped" id="table-healths">
      <thead>
        <tr>
          <th rowspan="2">日付</th>
          <th rowspan="2">曜日</th>
          <th colspan="2">体情報</th>
          <th colspan="3">睡眠情報</th>
          <th rowspan="2">水分</th>
          <th rowspan="2">お通じ</th>
          <th rowspan="2">編集</th>
        </tr>
        <tr>
          <th>体重</th>
          <th>体脂肪</th>
          <th>就寝時間(前日)</th>
          <th>起床時間</th>
          <th>睡眠時間</th>
        </tr>
      </thead>
  
      <tbody>
        <% @healths.each do |h| %>
          <tr>
            <!-- 日付 -->
            <td class='<%= css_class(h.day) %> pr-0 pl-0'><%= l(h.day, format: :short) %></td>
            <!-- 曜日 -->
            <td class='<%= css_class(h.day) %>'>
              <%= $days_of_the_week[h.day.wday] %>
            </td>
            <!-- 体重 -->
            <td>
              <% if h.weight.present? %>
                <%= h.weight %>
                <%= 'kg' %>
              <% end %>
            </td>
            <!-- 体脂肪 -->
            <td>
              <% if h.body_fat.present? %>
                <%= h.body_fat %>
                <%= '%' %>
              <% end %>
            </td>
            <!-- 就寝時間 -->
            <td>
              <% if h.bedtime_at.present?  %>
                <%= l(h.bedtime_at, format: :short) %>
              <% end %>
            </td>
            <!-- 起床時間 -->
            <td>
              <% if h.getuptime_at.present? %>
                <%= l(h.getuptime_at, format: :short) %>
              <% end %>
            </td>
            <!-- 睡眠時間 -->
            <td>
              <% if h.bedtime_at.present? && h.getuptime_at.present? %>
                <%= sleeping_time(h, h.bedtime_at, h.getuptime_at) %>
              <% end %>
            </td>
            <!-- 水分 -->
            <td>
              <% if h.water == true %>
                <%= "摂取あり" %>
              <% end %>
            </td>
            <!-- お通じ -->
            <td>
              <% if h.bowel_movement == true %>
                <%= "あり" %>
              <% end %>
            </td>
            <!-- 編集 -->
            <td>
              <div class="font-edit">
              <% if h.day <= Date.today %>
                <%= link_to user_healths_edit_day_path(@user.user_id, h.id), remote: true, class: "font-edit" do %> 
                  <%= icon('fa','edit') %>
                <% end %>
              <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>

<div id="edit" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit_day" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>