config/routes.rb
Rails.application.routes.draw do
  
  get 'profiles/edit'
  get 'users/index'
  get 'users/show'
  root 'homes#index'
  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions => 'users/sessions',
   :omniauth_callbacks => 'users/omniauth_callbacks'
  }

  resources :users do
    resources :profiles, only: [:edit, :update]
    resources :healths
      get 'healths/:id/edit_body', to: 'healths#edit_body', as: 'healths_edit_body'
      patch 'healths/:id/update_body', to: 'healths#update_body', as: 'healths_update_body'
      get 'healths/:id/edit_sleep', to: 'healths#edit_sleep', as: 'healths_edit_sleep'
      patch 'healths/:id/update_sleep', to: 'healths#update_sleep', as: 'healths_update_sleep'
      get 'healths/:id/edit_water', to: 'healths#edit_water', as: 'healths_edit_water'
      patch 'healths/:id/update_water', to: 'healths#update_water', as: 'healths_update_water'
      get 'healths/:id/edit_day', to: 'healths#edit_day', as: 'healths_edit_day'
      patch 'healths/:id/update_day', to: 'healths#update_day', as: 'healths_update_day'
  end
  resources :articles
end

app/views/shared/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %>" role="alert" id="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <div class='fixed-top'>
    <nav class="navbar navbar-expand-lg ">
      <%= link_to "My Log", root_path, class: "navbar-brand #{yield(:navbar_text)}" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon <%= yield(:navbar_text) %>"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
  
        <ul class="navbar-nav mr-auto">
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle <%= yield(:navbar_text) %>" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Diary
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Diary", articles_path, class: "dropdown-item" %>
                <%= link_to "New Diary", new_article_path, class: "dropdown-item" %>
              </div>
            </li>
            <li class="nav-item">
              <%= link_to "Health", user_path(current_user), class: "nav-link #{yield(:navbar_text)}" %>
            </li>
            <li class="nav-item d-block d-sm-none">
              <%= link_to "履歴", edit_user_path(current_user), class: "nav-link #{yield(:navbar_text)}" %>
            </li>
          <% end %>
        </ul>
        
        <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'アカウント編集', edit_user_registration_path, class: "nav-link #{yield(:navbar_text)}" %>
          </li>
          <li class="nav-item">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link #{yield(:navbar_text)}" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "アカウント登録", new_user_registration_path, class: "nav-link #{yield(:navbar_text)}" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: "nav-link #{yield(:navbar_text)}" %>
          </li>
        <% end %>
        </ul>
      </div>
    </nav>
  </div>
</header>